name: test_ui

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run tests
      run: pytest --alluredir=allure-results
    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre
        wget https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.18.1.tgz
        tar -zxvf allure-2.18.1.tgz
        sudo mv allure-2.18.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure
    - name: Generate Allure Report
      run: allure generate allure-results --clean -o allure-report
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.6.3
      with:
        token: ${{ secrets.CI_TOKEN }}
        branch: gh-pages
        folder: allure-report
        clean: true